---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: usernamespaces.usernamespace.gpte.redhat.com
spec:
  group: usernamespace.gpte.redhat.com
  version: v1
  scope: Cluster
  names:
    plural: usernamespaces
    singular: usernamespace
    kind: UserNamespace
    shortNames: []
  subresources:
    status: {}
